spring:
  application:
    name: reserva-de-eventos-aluran1
  datasource:
    url: jdbc:postgresql://
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
