spring:
  application:
    name: reserva-de-eventos-aluran1
  datasource:
    url: jdbc:postgresql://ep-empty-band-acorj4z0-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update